openapi: 3.0.0
info:
  title: Cortex XDR
  description: Retrieve incidents from Cortex XDR with simplified parameters.
  version: "1.0.0"
servers:
  - url: https://api-gpf.xdr.eu.paloaltonetworks.com

paths:
  /public_api/v1/incidents/get_incidents/:
    post:
      summary: Get All Incidents
      description: Retrieve a list of incidents from Cortex XDR.
      operationId: getAllIncidents
      parameters:
        - in: header
          name: x-xdr-auth-id
          schema:
            type: string
          required: true
          description: Default is 55
        - name: page
          in: query
          required: false
          schema:
            type: integer
            example: 1
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            example: 50
        - name: sort
          in: query
          required: false
          schema:
            type: string
            example: "desc"
      requestBody:
          content: {"request_data":{}}
      responses:
        '200':
          description: Successful retrieval of incidents.
          content:
            application/json:
              schema:
                type: object
                properties:
                  incident_id:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  creation_time:
                    type: string
                    format: date-time
                  last_modified:
                    type: string
                    format: date-time
        '400':
          description: Bad request.
        '401':
          description: Unauthorized.
        '500':
          description: Internal server error.

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization  # This is for the API key
    xdrAuthId:
      type: apiKey
      in: header
      name: x-xdr-auth-id  # This is for the API key ID

security:
  - ApiKeyAuth: []
  - xdrAuthId: []
