openapi: 3.0.0

info:
    title: Fetch details from Cortex
    description: The skills in this plugin will get different information from Cortex
    version: "v1"

# This should point to the Azure Function URL
servers:
    - url: https://ebla-cortex-omar.azurewebsites.net/api/

paths:
    /cortex_get_incidents?op=GetIncidents:
        get:
            operationId: GetIncidents
            description: Get list of incidents
            parameters:
                - in: query
                  name: data
                  schema:
                      type: string
                  required: true
                  description: Filter parameters
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
