openapi: 3.0.0
 
info:
    title: Fetch details from Cortex
    description: The skills in this plugin will get different information from Cortex
    version: "1.0.0"
 
 
servers:
    - url: https://kia-cortex-xdr.azurewebsites.net/api/
 
paths:
    /cortex_get_incidents?op=GetIncidents:
        post:
            operationId: GetIncidents
            description: Get list of incidents
            parameters:
                - in: query
                  name: data
                  schema:
                      type: string
                  required: true
                  description: Filter parameters
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
