openapi: 3.0.0

info:
    title: "Fetch details from Cortex"
    description: "The skills in this plugin will get different information from Cortex"
    version: 1.0.0

# This should point to the Azure Function URL
servers:
    - url: "https://[Azure-Function-Default-domain]/api/"

paths:
    /[Get-Function-URL]&op=GetIncidents&data=1:
        get:
            operationId: GetIncidents
            description: Get list of incidents
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                type: object
                properties:
                  incident_id:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  creation_time:
                    type: string
                    format: date-time
