openapi: 3.0.0

info:
  title: Taegis Vulnerability Management API
  description: Retrieve a list of vulnerability groups using the Taegis Vulnerability Management API
  version: "v1"

servers:
  - url: https://api.taegis.com/api/v2

paths:
  /vulnerability-groups:
    get:
      operationId: getVulnerabilityGroups
      summary: Retrieve a list of vulnerability groups
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            default: 50
          required: false
          description: Number of results per page.
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
          required: false
          description: The index at which results start.
        - in: query
          name: sort
          schema:
            type: string
          required: false
          description: Sort modes as a comma-separated list. Available sort keys include assessment_date, base_score, description, priority, etc.
        - in: query
          name: q
          schema:
            type: string
          required: false
          description: JSON format search grammar. Example: {"global":{"text": "XSS"}}.
      responses:
        "200":
          description: Successful retrieval of vulnerability group list
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VulnerabilityGroupListResponse"

components:
  schemas:
    VulnerabilityGroupListResponse:
      type: object
      properties:
        currentItemCount:
          type: integer
          description: Current item count in the result set.
        items:
          type: array
          items:
            type: object
            properties:
              assessmentDate:
                type: string
                format: date-time
                description: Date of the vulnerability assessment.
              assetHostname:
                type: string
                description: Hostname of the asset.
              assetId:
                type: string
                description: Identifier of the asset.
              assetLocation:
                type: string
                description: Location of the asset.
              cvss:
                type: number
                description: CVSS score of the vulnerability group.
              definitionId:
                type: string
                description: Definition ID for the vulnerability group.
              fields:
                type: string
                description: Fields related to the vulnerability group.
              firstDiscoveryDate:
                type: string
                format: date-time
                description: Date of first discovery.
              groupingStrategy:
                type: string
                description: Strategy used for grouping vulnerabilities.
              hasVerified:
                type: boolean
                description: Indicates if any vulnerabilities in the group are verified.
              id:
                type: string
                description: Unique identifier of the vulnerability group.
              isFixed:
                type: boolean
                description: Whether the vulnerabilities in the group are fixed.
              isSnoozed:
                type: boolean
                description: Whether the vulnerabilities in the group are snoozed.
              isVerified:
                type: boolean
                description: Whether the vulnerabilities in the group are verified.
              kind:
                type: string
                description: Type of vulnerability group.
              lastSeenDate:
                type: string
                format: date-time
                description: Date when the group was last seen.
              name:
                type: string
                description: Name of the vulnerability group.
              noteContent:
                type: string
                description: Notes related to the vulnerability group.
              pciFailCount:
                type: integer
                description: Number of PCI failures in the group.
              pciPassCount:
                type: integer
                description: Number of PCI passes in the group.
              score:
                type: number
                description: Score assigned to the group.
              snoozedUntilDate:
                type: string
                format: date-time
                description: Date until which the group is snoozed.
              traceableId:
                type: string
                description: Traceable ID of the vulnerability group.
              verifyDate:
                type: string
                format: date-time
                description: Date when the group was verified.
              verifyUserIds:
                type: array
                items:
                  type: string
                description: List of user IDs who verified the group.
        itemsPerPage:
          type: integer
          description: Number of items per page.
        pagingLinkTemplate:
          type: string
          description: Template for pagination links.
        startIndex:
          type: integer
          description: Starting index of the results.
        totalItems:
          type: integer
          description: Total items in the result set.
