openapi: 3.0.0

info:
  title: Taegis Vulnerability Management API
  description: Retrieve details of a specific vulnerability using the Taegis Vulnerability Management API
  version: "v1"

servers:
  - url: https://api.taegis.com/api/v2

paths:
  /vulnerabilities/{id}:
    get:
      operationId: getVulnerabilityById
      summary: Retrieve details of a specific vulnerability by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The unique identifier of the vulnerability.
      responses:
        "200":
          description: Successful retrieval of vulnerability details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VulnerabilityDetailResponse"

components:
  schemas:
    VulnerabilityDetailResponse:
      type: object
      properties:
        assessmentDate:
          type: string
          format: date-time
          description: Date the vulnerability was assessed.
        assessmentUserId:
          type: string
          description: User ID of the assessor.
        assetId:
          type: string
          description: Asset identifier associated with the vulnerability.
        cveNumber:
          type: string
          description: CVE number linked to the vulnerability.
        cvss:
          type: number
          description: CVSS score of the vulnerability.
        definitionId:
          type: string
          description: Definition ID of the vulnerability.
        detail:
          type: string
          description: Detailed description of the vulnerability.
        detectionId:
          type: string
          description: Detection ID related to the vulnerability.
        detectionTraceableId:
          type: string
          description: Detection traceable ID.
        fields:
          type: string
          description: Fields related to the vulnerability.
        firstDiscoveryDate:
          type: string
          format: date-time
          description: Date when the vulnerability was first discovered.
        fixedInVersion:
          type: string
          description: Version in which the vulnerability is fixed.
        harLink:
          type: string
          description: Link to HAR file related to the vulnerability.
        host:
          type: string
          description: Host associated with the vulnerability.
        httpCode:
          type: string
          description: HTTP code related to the vulnerability.
        httpMethod:
          type: string
          description: HTTP method used in vulnerability exploitation.
        id:
          type: string
          description: Unique identifier for the vulnerability.
        installedVersion:
          type: string
          description: Installed version of the affected software.
        isFixed:
          type: boolean
          description: Whether the vulnerability has been fixed.
        isSnoozed:
          type: boolean
          description: Whether the vulnerability is snoozed.
        isVerified:
          type: boolean
          description: Whether the vulnerability is verified.
        kind:
          type: string
          description: Type or category of the vulnerability.
        lastSeenDate:
          type: string
          format: date-time
          description: Date when the vulnerability was last seen.
        name:
          type: string
          description: Name of the vulnerability.
        param:
          type: string
          description: Parameter involved in the vulnerability.
        payload:
          type: string
          description: Payload related to the vulnerability.
        pciCustomerNote:
          type: string
          description: Customer note for PCI compliance.
        pciSystemNote:
          type: string
          description: System note for PCI compliance.
        pciVendorNote:
          type: string
          description: Vendor note for PCI compliance.
        port:
          type: string
          description: Network port associated with the vulnerability.
        protocol:
          type: string
          description: Protocol used in vulnerability exploitation.
        score:
          type: number
          description: Score assigned to the vulnerability.
        snoozeUntilDate:
          type: string
          format: date-time
          description: Date until which the vulnerability is snoozed.
        software:
          type: string
          description: Affected software.
        url:
          type: string
          description: URL associated with the vulnerability.
        verifyDate:
          type: string
          format: date-time
          description: Date when the vulnerability was verified.
        verifyUserId:
          type: string
          description: User ID of the verifier.
        vulnerabilityTraceableId:
          type: string
          description: Traceable ID for tracking the vulnerability.
